services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: snesa
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mariadb:10.11
        container_name: mariadb_db
        
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel_db}
            MYSQL_USER: ${DB_USERNAME:-laravel_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_secret}
            
        volumes:
            - ./storage/database:/var/lib/mysql